### ISSUE TITLE
Issues with using LRUStoreCache after invalidation

### ISSUE THREAD

**Issue by BGCMHou** [zarr-developers/zarr-python#1076]
#### Minimal, reproducible code sample, a copy-pastable example if possible

```python
import zarr 

store = <create store here>
cache = zarr.LRUStoreCache(store, <set max size to be the size of one data item>)
<use cache to get data>
cache.invalidate()
<use cache to get data again> 

```

#### Problem description

I am currently using the LRUStoreCache and need to periodically invalidate it. I receive the following error after I have invalidated a previously full cache: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2426, in __getitem__
    value = self._values_cache[key]
KeyError: '.zmetadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...my code calling zarr open_consolidated...
  File "/usr/local/lib/python3.8/site-packages/zarr/convenience.py", line 1304, in open_consolidated
    meta_store = ConsolidatedStoreClass(store, metadata_key=metadata_key)
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2853, in __init__
    meta = json_loads(self.store[metadata_key])
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2440, in __getitem__
    self._cache_value(key, value)
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2392, in _cache_value
    self._accommodate_value(value_size)
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2383, in _accommodate_value
    v = self._pop_value()
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2375, in _pop_value
    _, v = self._values_cache.popitem(last=False)
KeyError: 'dictionary is empty'
[2022-07-13 22:57:06,009] ERROR in app: Exception on /api/thresholds [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2426, in __getitem__
    value = self._values_cache[key]
KeyError: '.zmetadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ... my code calling zarr open_consolidated...
  File "/usr/local/lib/python3.8/site-packages/zarr/convenience.py", line 1304, in open_consolidated
    meta_store = ConsolidatedStoreClass(store, metadata_key=metadata_key)
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2853, in __init__
    meta = json_loads(self.store[metadata_key])
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2440, in __getitem__
    self._cache_value(key, value)
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2392, in _cache_value
    self._accommodate_value(value_size)
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2383, in _accommodate_value
    v = self._pop_value()
  File "/usr/local/lib/python3.8/site-packages/zarr/storage.py", line 2375, in _pop_value
    _, v = self._values_cache.popitem(last=False)
KeyError: 'dictionary is empty'
```
I believe I am receiving this error because the [invalidate](https://github.com/zarr-developers/zarr-python/blob/9ce2f328e9ff687c151cd73634f4d624590df817/zarr/storage.py#L2396) function (storage.py, line 2396) clears the cache's values but does not reset the current size to zero (i.e., the cache current size is still at the max size). Thus, when I try to get an item after invalidation, the cache believes it needs to accommodate space for the item (it passes the if statement in  [_accomodate_value ](https://github.com/zarr-developers/zarr-python/blob/9ce2f328e9ff687c151cd73634f4d624590df817/zarr/storage.py#L2378)(storage.py, line 2378)).  The cache then tries to pop a value, but it cannot because the values have recently been cleared through invalidation. Thus, the `KeyError: 'dictionary is empty'` is thrown. 

#### Version and installation information
zarr: 2.12.0
numcodecs: 0.6.4
python interpreter: 3.8
Operating system: Windows

Zarr was installed using pip into a docker environment.

**Comment by joshmoore** [comment]
Could you include the configuration of the store as well? This could be related to the consolidated store since that adds one extra key which could have upset the counts.

**Comment by BGCMHou** [comment]
Thanks for the quick reply! I am using an ABSStore: 
```
container_client = ContainerClient(<url>, <container_name>)
store = zarr.ABSStore(client=container_client, prefix=<prefix>)
cache = zarr.LRUStoreCache(store, 221184000)
```

The zarr file in the the blob storage container is consolidated and `.zmetadata` is present.  My code is calling `zarr.open_consolidated(store, mode='r')` and it works until I invalidate a full cache.  (However, it does not break after cache invalidation if the cache was not full).

**Comment by joshmoore** [comment]
What happens if you call `zarr.open_consolidated(cache, ...)` rather than on the store, creating a strict _sequence_ of store wrappers rather than multiple entry points (`cache` and `consolidated_store`)?

**Comment by BGCMHou** [comment]
Sorry, I mistyped. I am currently calling `zarr.open_consolidated(cache, mode='r')` not `zarr.open_consolidated(store, mode='r')`. Overriding the `invalidate` function in LRUStoreCache seems to have fixed my problem:
``` 
class LRUStoreCache(zarr.LRUStoreCache):
    def invalidate(self):
        super().invalidate()
        self._current_size = 0

zarr.LRUStoreCache = LRUStoreCache
```

**Comment by joshmoore** [comment]
Nice! Do you want to see if that change as a PR passes CI?

**Comment by BGCMHou** [comment]
yes, please. Thanks!
