### ISSUE TITLE
Tag v.2.13.2 breaks setuptools_scm

### ISSUE THREAD

**Issue by jhamman** [zarr-developers/zarr-python#1147]
### Zarr version

v.2.13.2

### Numcodecs version

0.10.2

### Python Version

3.9.13

### Operating System

Mac (M1)

### Installation

tried using conda and venv

### Description

The most recent tag [v.2.13.2](https://github.com/zarr-developers/zarr-python/releases/tag/v.2.13.2) has an extra `.` after the `v`. This seems to be breaking `setuptools_scm`'s automatic version extraction:

<details>

```
~/Dropbox/src/zarr-python main ❯ pip install -e .                                                                       Py zarr-dev Py base 10:09:19
Obtaining file:///Users/jhamman/Dropbox%20%28Personal%29/src/zarr-python
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      /private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/normal/lib/python3.9/site-packages/setuptools_scm/version.py:84: UserWarning: tag 'v.2.13.2' no version found
        warnings.warn(f"tag {tag!r} no version found")
      Traceback (most recent call last):
        File "/Users/jhamman/pyenv/zarr-dev/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/jhamman/pyenv/zarr-dev/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/jhamman/pyenv/zarr-dev/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 191, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 449, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 16, in <module>
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/normal/lib/python3.9/site-packages/setuptools_scm/integration.py", line 90, in version_keyword
          _assign_version(dist, config)
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/normal/lib/python3.9/site-packages/setuptools_scm/integration.py", line 59, in _assign_version
          maybe_version = _get_version(config)
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/normal/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 154, in _get_version
          parsed_version = _do_parse(config)
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/normal/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 101, in _do_parse
          version = _version_from_entrypoints(config) or _version_from_entrypoints(
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/normal/lib/python3.9/site-packages/setuptools_scm/_entrypoints.py", line 66, in _version_from_entrypoints
          version: ScmVersion | None = _call_entrypoint_fn(root, config, ep.load())
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/normal/lib/python3.9/site-packages/setuptools_scm/_entrypoints.py", line 40, in _call_entrypoint_fn
          return fn(root, config=config)
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/normal/lib/python3.9/site-packages/setuptools_scm/git.py", line 181, in parse
          return _git_parse_inner(
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/normal/lib/python3.9/site-packages/setuptools_scm/git.py", line 224, in _git_parse_inner
          return meta(
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/normal/lib/python3.9/site-packages/setuptools_scm/version.py", line 226, in meta
          parsed_version = _parse_tag(tag, preformatted, config)
        File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-build-env-ekl64pj4/normal/lib/python3.9/site-packages/setuptools_scm/version.py", line 203, in _parse_tag
          assert version is not None
      AssertionError
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

</details>

### Steps to reproduce

```
git clone git@github.com:zarr-developers/zarr-python.git
cd zarr-python
git remote add upstream git@github.com:zarr-developers/zarr-python.git

mkdir -p ~/pyenv/zarr-dev-test
python -m venv ~/pyenv/zarr-dev-test
source ~/pyenv/zarr-dev-test/bin/activate
pip install -r requirements_dev_minimal.txt -r requirements_dev_numpy.txt
pip install -e .
```

### Additional output

The following patch in my local repo seems to be working:

```
git tag v2.13.2
git tag -d v.2.13.2
```

**Comment by joshmoore** [comment]
Thanks, @jhamman. Guess my frustrations with fighting the conda-forge tests are showing! 🤦🏽 

I've retracted the previous release (and deleted the tag) and published https://github.com/zarr-developers/zarr-python/releases/tag/v2.13.2

Hopefully things will now go green.

**Comment by jhamman** [comment]
Thanks @joshmoore!
