### ISSUE TITLE
ValueError on empty slice after resize() with fsspec store

### ISSUE THREAD

**Issue by sbalmer** [zarr-developers/zarr-python#1341]
When using fsspec as store, the Array throws a ValueError when selecting an empty slice(), but only after resizing:

```
import fsspec
import zarr

fs = fsspec.filesystem('memory')
store = zarr.storage.FSStore('/test', fs=fs)
arr = zarr.create((0,), store=store)

# These print "[]" as expected
print(arr[0:0])
print(arr[1:1])

arr.resize((1,))

# These raise ValueError
print(arr[0:0])
print(arr[1:1])

```

**Comment by sbalmer** [comment]
I'm using `fsspec==2023.1.0` and `zarr== 2.13.6`.

The traceback is

```
>>> print(arr[0:0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/zarr/core.py", line 807, in __getitem__
    result = self.get_basic_selection(pure_selection, fields=fields)
  File "/usr/local/lib/python3.9/site-packages/zarr/core.py", line 933, in get_basic_selection
    return self._get_basic_selection_nd(selection=selection, out=out,
  File "/usr/local/lib/python3.9/site-packages/zarr/core.py", line 976, in _get_basic_selection_nd
    return self._get_selection(indexer=indexer, out=out, fields=fields)
  File "/usr/local/lib/python3.9/site-packages/zarr/core.py", line 1271, in _get_selection
    lchunk_coords, lchunk_selection, lout_selection = zip(*indexer)
ValueError: not enough values to unpack (expected 3, got 0)
```

**Comment by d-v-b** [comment]
this works today:

```python
"""Reproducer for zarr-developers/zarr-python#1341.

v2 (2.13.6): after resize(), selecting an empty slice on an fsspec-backed
array raised
    ValueError: not enough values to unpack (expected 3, got 0)
Expected: empty selections print [] both before and after the resize.

v3 adaptation: FSStore('/test', fs=memory_fs) -> FsspecStore.from_url("memory://test").
"""
import zarr

print("zarr:", zarr.__version__)

store = zarr.storage.FsspecStore.from_url("memory://test")
arr = zarr.create((0,), store=store)

failures = []

def check(label, fn):
    try:
        print(f"{label}: {fn()!r}")
    except ValueError as e:
        print(f"{label}: ValueError: {e}")
        failures.append(label)

# These printed "[]" as expected on v2 too
check("before resize arr[0:0]", lambda: arr[0:0])
check("before resize arr[1:1]", lambda: arr[1:1])

arr.resize((1,))

# These raised ValueError on v2
check("after resize  arr[0:0]", lambda: arr[0:0])
check("after resize  arr[1:1]", lambda: arr[1:1])

print()
if failures:
    print("REPRODUCED — ValueError on:", ", ".join(failures))
    raise SystemExit(1)
print("NOT REPRODUCED — all empty slices returned cleanly")

```
