### ISSUE TITLE
ValueError: codec not available: 'blosc2'

### ISSUE THREAD

**Issue by bakamotokatas** [zarr-developers/zarr-python#1637]
### Zarr version

v2.16.1

### Numcodecs version

v0.12.1

### Python Version

3.11.6

### Operating System

Manjaro Linux

### Installation

using system package manager aur

### Description

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/xarray/backends/zarr.py", line 824, in open_zarr
    ds = open_dataset(
         ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xarray/backends/api.py", line 541, in open_dataset
    backend_ds = backend.open_dataset(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xarray/backends/zarr.py", line 902, in open_dataset
    ds = store_entrypoint.open_dataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xarray/backends/store.py", line 32, in open_dataset
    vars, attrs = store.load()
                  ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xarray/backends/common.py", line 128, in load
    (_decode_variable_name(k), v) for k, v in self.get_variables().items()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xarray/backends/zarr.py", line 485, in get_variables
    return FrozenDict(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xarray/core/utils.py", line 469, in FrozenDict
    return Frozen(dict(*args, **kwargs))
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xarray/backends/zarr.py", line 485, in <genexpr>
    return FrozenDict(
                     ^
  File "/usr/lib/python3.11/site-packages/zarr/hierarchy.py", line 673, in _array_iter
    yield _key if keys_only else (_key, self[key])
                                        ~~~~^^^^^
  File "/usr/lib/python3.11/site-packages/zarr/hierarchy.py", line 462, in __getitem__
    return Array(
           ^^^^^^
  File "/usr/lib/python3.11/site-packages/zarr/core.py", line 224, in __init__
    self._load_metadata()
  File "/usr/lib/python3.11/site-packages/zarr/core.py", line 243, in _load_metadata
    self._load_metadata_nosync()
  File "/usr/lib/python3.11/site-packages/zarr/core.py", line 291, in _load_metadata_nosync
    self._compressor = get_codec(compressor)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/numcodecs/registry.py", line 56, in get_codec
    raise ValueError('codec not available: %r' % codec_id)
ValueError: codec not available: 'blosc2'
```

it gives blosc2 error

### Steps to reproduce

```
import xarray as xr
xr.open_zarr("/home/bakamotokatas/Downloads/icon-eu/20200101_00.zarr.zip")
```

**Comment by jhamman** [comment]
@bakamotokatas - the blosc codec in numcodecs has an id of `blosc`, not `blosc2`. Can you share your array metadata (`.zarray`)? Do you know how this dataset was created? Is it possible someone used a custom codec to create this dataset?

**Comment by jhamman** [comment]
closing as stale, feel free to reopen if you are still running into this issue.
