### ISSUE TITLE
Scalar arrays and oindex

### ISSUE THREAD

**Issue by thomascoquet** [zarr-developers/zarr-python#302]
```
import zarr
store = zarr.DirectoryStore('data')
r = zarr.open_group(store=store)
z = r.full('myArray', 42, shape=(), dtype='i4', compressor=None)

print(z.oindex[...])
```

#### Problem description

The above code raises an exception 
```
Traceback (most recent call last):
  File "/home/tom/PycharmProjects/starling-hcs/forest-penrose-zcube/examples/example_raster.py", line 10, in <module>
    print(z2.oindex[...])
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/indexing.py", line 601, in __getitem__
    return self.array.get_orthogonal_selection(selection, fields=fields)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/core.py", line 838, in get_orthogonal_selection
    return self._get_selection(indexer=indexer, out=out, fields=fields)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/core.py", line 1015, in _get_selection
    drop_axes=indexer.drop_axes, fields=fields)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/core.py", line 1558, in _chunk_getitem
    assert len(chunk_coords) == len(self._cdata_shape)
AssertionError
```
Looks like this indexer is not handling properly the case of scalar arrays.

#### Version and installation information
python 3.6
zarr 2.2.0
numcodecs 0.5.5
Ubuntu

Thank you !

**Comment by alimanfoo** [comment]
Thanks Thomas. I'm not 100% sure it makes sense to use oindex (or vindex)
on a scalar. But maybe the best thing to do here would be to check within
oindex and vindex if the array is scalar, if so to pass on to the scalar
indexing code already in place to handle indexing via __getitem__. PR would
be welcome.

**Comment by dstansby** [comment]
Seems to work on 2.18.3, so I'll close as fixed 🎉
