### ISSUE TITLE
'FSMap' object has no attribute 'missing_exceptions'

### ISSUE THREAD

**Issue by v2thegreat** [zarr-developers/zarr-python#646]
#### Minimal, reproducible code sample, a copy-pastable example if possible

```python

s3_file_system = s3fs.S3FileSystem()

def read_zar_file(s3_path, chunks = 'auto', is_consolidated=True):
    # Initilize the S3 file system
    s3_file_system = s3fs.S3FileSystem()
    store = s3fs.S3Map(root=s3_path, s3=s3_file_system, check=False)
    return xr.open_zarr(store=store, consolidated=is_consolidated, chunks = chunks)

failed = []
for file in tqdm(input_dataset_files):
    dataset = read_zar_file(file)
    var = list(dataset.keys())[0]
    dataset[var].mean(dim='time').plot()
```

<details><summary>Error Traceback</summary>

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-a33923c4bda1> in <module>
      3     dataset = read_zar_file(file)
      4     var = list(dataset.keys())[0]
----> 5     dataset[var].mean(dim='time').plot()

~/miniconda3/envs/main/lib/python3.6/site-packages/xarray/plot/plot.py in __call__(self, **kwargs)
    444 
    445     def __call__(self, **kwargs):
--> 446         return plot(self._da, **kwargs)
    447 
    448     @functools.wraps(hist)

~/miniconda3/envs/main/lib/python3.6/site-packages/xarray/plot/plot.py in plot(darray, row, col, col_wrap, ax, hue, rtol, subplot_kws, **kwargs)
    162 
    163     """
--> 164     darray = darray.squeeze().compute()
    165 
    166     plot_dims = set(darray.dims)

~/miniconda3/envs/main/lib/python3.6/site-packages/xarray/core/dataarray.py in compute(self, **kwargs)
    825         """
    826         new = self.copy(deep=False)
--> 827         return new.load(**kwargs)
    828 
    829     def persist(self, **kwargs) -> "DataArray":

~/miniconda3/envs/main/lib/python3.6/site-packages/xarray/core/dataarray.py in load(self, **kwargs)
    799         dask.array.compute
    800         """
--> 801         ds = self._to_temp_dataset().load(**kwargs)
    802         new = self._from_temp_dataset(ds)
    803         self._variable = new._variable

~/miniconda3/envs/main/lib/python3.6/site-packages/xarray/core/dataset.py in load(self, **kwargs)
    649 
    650             # evaluate all the dask arrays simultaneously
--> 651             evaluated_data = da.compute(*lazy_data.values(), **kwargs)
    652 
    653             for k, data in zip(lazy_data, evaluated_data):

~/miniconda3/envs/main/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    435     keys = [x.__dask_keys__() for x in collections]
    436     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 437     results = schedule(dsk, keys, **kwargs)
    438     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    439 

~/miniconda3/envs/main/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2723                     should_rejoin = False
   2724             try:
-> 2725                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2726             finally:
   2727                 for f in futures.values():

~/miniconda3/envs/main/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1990                 direct=direct,
   1991                 local_worker=local_worker,
-> 1992                 asynchronous=asynchronous,
   1993             )
   1994 

~/miniconda3/envs/main/lib/python3.6/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    831         else:
    832             return sync(
--> 833                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    834             )
    835 

~/miniconda3/envs/main/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]

~/miniconda3/envs/main/lib/python3.6/site-packages/distributed/utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()

~/miniconda3/envs/main/lib/python3.6/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/miniconda3/envs/main/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1849                             exc = CancelledError(key)
   1850                         else:
-> 1851                             raise exception.with_traceback(traceback)
   1852                         raise exc
   1853                     if errors == "skip":

~/miniconda3/envs/main/lib/python3.6/site-packages/dask/array/core.py in getter()
    104         c = a[b]
    105         if asarray:
--> 106             c = np.asarray(c)
    107     finally:
    108         if lock:

~/miniconda3/envs/main/lib/python3.6/site-packages/numpy/core/_asarray.py in asarray()
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

~/miniconda3/envs/main/lib/python3.6/site-packages/xarray/core/indexing.py in __array__()
    489 
    490     def __array__(self, dtype=None):
--> 491         return np.asarray(self.array, dtype=dtype)
    492 
    493     def __getitem__(self, key):

~/miniconda3/envs/main/lib/python3.6/site-packages/numpy/core/_asarray.py in asarray()
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

~/miniconda3/envs/main/lib/python3.6/site-packages/xarray/core/indexing.py in __array__()
    555     def __array__(self, dtype=None):
    556         array = as_indexable(self.array)
--> 557         return np.asarray(array[self.key], dtype=None)
    558 
    559     def transpose(self, order):

~/miniconda3/envs/main/lib/python3.6/site-packages/xarray/backends/zarr.py in __getitem__()
     47         array = self.get_array()
     48         if isinstance(key, indexing.BasicIndexer):
---> 49             return array[key.tuple]
     50         elif isinstance(key, indexing.VectorizedIndexer):
     51             return array.vindex[

~/miniconda3/envs/main/lib/python3.6/site-packages/zarr/core.py in __getitem__()
    569 
    570         fields, selection = pop_fields(selection)
--> 571         return self.get_basic_selection(selection, fields=fields)
    572 
    573     def get_basic_selection(self, selection=Ellipsis, out=None, fields=None):

~/miniconda3/envs/main/lib/python3.6/site-packages/zarr/core.py in get_basic_selection()
    695         else:
    696             return self._get_basic_selection_nd(selection=selection, out=out,
--> 697                                                 fields=fields)
    698 
    699     def _get_basic_selection_zd(self, selection, out=None, fields=None):

~/miniconda3/envs/main/lib/python3.6/site-packages/zarr/core.py in _get_basic_selection_nd()
    737         indexer = BasicIndexer(selection, self)
    738 
--> 739         return self._get_selection(indexer=indexer, out=out, fields=fields)
    740 
    741     def get_orthogonal_selection(self, selection, out=None, fields=None):

~/miniconda3/envs/main/lib/python3.6/site-packages/zarr/core.py in _get_selection()
   1032             lchunk_coords, lchunk_selection, lout_selection = zip(*indexer)
   1033             self._chunk_getitems(lchunk_coords, lchunk_selection, out, lout_selection,
-> 1034                                  drop_axes=indexer.drop_axes, fields=fields)
   1035 
   1036         if out.shape:

~/miniconda3/envs/main/lib/python3.6/site-packages/zarr/core.py in _chunk_getitems()
   1664 
   1665         ckeys = [self._chunk_key(ch) for ch in lchunk_coords]
-> 1666         cdatas = self.chunk_store.getitems(ckeys)
   1667         for ckey, chunk_select, out_select in zip(ckeys, lchunk_selection, lout_selection):
   1668             if ckey in cdatas:

~/miniconda3/envs/main/lib/python3.6/site-packages/fsspec/mapping.py in getitems()
     92         out = {
     93             k: (KeyError() if isinstance(v, self.missing_exceptions) else v)
---> 94             for k, v in out.items()
     95         }
     96         return {

~/miniconda3/envs/main/lib/python3.6/site-packages/fsspec/mapping.py in <dictcomp>()
     92         out = {
     93             k: (KeyError() if isinstance(v, self.missing_exceptions) else v)
---> 94             for k, v in out.items()
     95         }
     96         return {

AttributeError: 'FSMap' object has no attribute 'missing_exceptions'
```
</details>

#### Problem description

I was trying to get my dataset to merge, but I'm unable to access and work with it. It's stored as a zarr directory in S3 right now.

Ideally, I would be able to stream this data and compute the mean without any problems and have been successful in the past

This script has worked in some cases as well and was working until today. Without more clarification, I don't know what might be relevant and what might not be. 

I posted this issue in xarray as well here: https://github.com/pydata/xarray/issues/4563, please follow the thread to understand the steps that we've taken so far, and let me know what other issues you might have

#### Version and installation information

Installed via conda btw

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-1029-aws
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.1

xarray: 0.15.0
pandas: 0.25.3
numpy: 1.18.1
scipy: 1.4.1
netCDF4: 1.4.2
pydap: None
h5netcdf: 0.8.1
h5py: 2.10.0
Nio: None
zarr: 2.5.0
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.1.0
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2.11.0
distributed: 2.30.0
matplotlib: 3.1.3
cartopy: None
seaborn: None
numbagg: None
setuptools: 50.3.0.post20201006
pip: 20.2.4
conda: None
pytest: None
IPython: 7.16.1
sphinx: None

</details>

**Comment by rabernat** [comment]
Thanks for the bug report. This is the same as https://github.com/dask/gcsfs/issues/299

The [solution](https://github.com/dask/gcsfs/issues/299#issuecomment-716819049) is to upgrade fsspec to to version >= 0.8.4. Please try that and report back.

**Comment by v2thegreat** [comment]
That worked temporarily. The current error that I'm getting when uploading data to s3 from zarr is:

<details><summary>Error Log:</summary>

```python

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-35-afd4139dbe39> in <module>
----> 1 write_zar_file(ds, s3_path='s3://aquaoriginals/era5/test/')

<ipython-input-3-5c7a5767879b> in write_zar_file(dataset, s3_path, is_consolidated)
     11     s3_file_system = s3fs.S3FileSystem()
     12     store = s3fs.S3Map(root=s3_path, s3=s3_file_system, check=False)
---> 13     return dataset.to_zarr(store=store, consolidated=is_consolidated)

~/miniconda3/envs/main/lib/python3.6/site-packages/xarray/core/dataset.py in to_zarr(self, store, chunk_store, mode, synchronizer, group, encoding, compute, consolidated, append_dim)
   1660             compute=compute,
   1661             consolidated=consolidated,
-> 1662             append_dim=append_dim,
   1663         )
   1664 

~/miniconda3/envs/main/lib/python3.6/site-packages/xarray/backends/api.py in to_zarr(dataset, store, chunk_store, mode, synchronizer, group, encoding, compute, consolidated, append_dim)
   1361         group=group,
   1362         consolidate_on_close=consolidated,
-> 1363         chunk_store=chunk_store,
   1364     )
   1365     zstore.append_dim = append_dim

~/miniconda3/envs/main/lib/python3.6/site-packages/xarray/backends/zarr.py in open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close, chunk_store)
    290             zarr_group = zarr.open_consolidated(store, **open_kwargs)
    291         else:
--> 292             zarr_group = zarr.open_group(store, **open_kwargs)
    293         return cls(zarr_group, consolidate_on_close)
    294 

~/miniconda3/envs/main/lib/python3.6/site-packages/zarr/hierarchy.py in open_group(store, mode, cache_attrs, synchronizer, path, chunk_store, storage_options)
   1177             raise ContainsGroupError(path)
   1178         else:
-> 1179             init_group(store, path=path, chunk_store=chunk_store)
   1180 
   1181     # determine read only status

~/miniconda3/envs/main/lib/python3.6/site-packages/zarr/storage.py in init_group(store, overwrite, path, chunk_store)
    471     # initialise metadata
    472     _init_group_metadata(store=store, overwrite=overwrite, path=path,
--> 473                          chunk_store=chunk_store)
    474 
    475 

~/miniconda3/envs/main/lib/python3.6/site-packages/zarr/storage.py in _init_group_metadata(store, overwrite, path, chunk_store)
    497     meta = dict()  # type: ignore
    498     key = _path_to_prefix(path) + group_meta_key
--> 499     store[key] = encode_group_metadata(meta)
    500 
    501 

~/miniconda3/envs/main/lib/python3.6/site-packages/fsspec/mapping.py in __setitem__(self, key, value)
    151             # back compat, array.array used to work
    152             value = bytearray(value)
--> 153         self.fs.mkdirs(self.fs._parent(key), exist_ok=True)
    154         self.fs.pipe_file(key, value)
    155 

~/miniconda3/envs/main/lib/python3.6/site-packages/fsspec/spec.py in mkdirs(self, path, exist_ok)
   1075     def mkdirs(self, path, exist_ok=False):
   1076         """Alias of :ref:`FilesystemSpec.makedirs`."""
-> 1077         return self.makedirs(path, exist_ok=exist_ok)
   1078 
   1079     def listdir(self, path, detail=True, **kwargs):

~/miniconda3/envs/main/lib/python3.6/site-packages/s3fs/core.py in makedirs(self, path, exist_ok)
    486     def makedirs(self, path, exist_ok=False):
    487         try:
--> 488             self.mkdir(path, create_parents=True)
    489         except FileExistsError:
    490             if exist_ok:

~/miniconda3/envs/main/lib/python3.6/site-packages/fsspec/asyn.py in wrapper(*args, **kwargs)
    119     def wrapper(*args, **kwargs):
    120         self = obj or args[0]
--> 121         return maybe_sync(func, self, *args, **kwargs)
    122 
    123     return wrapper

~/miniconda3/envs/main/lib/python3.6/site-packages/fsspec/asyn.py in maybe_sync(func, self, *args, **kwargs)
     98         if inspect.iscoroutinefunction(func):
     99             # run the awaitable on the loop
--> 100             return sync(loop, func, *args, **kwargs)
    101         else:
    102             # just call the blocking function

~/miniconda3/envs/main/lib/python3.6/site-packages/fsspec/asyn.py in sync(loop, func, callback_timeout, *args, **kwargs)
     69     if error[0]:
     70         typ, exc, tb = error[0]
---> 71         raise exc.with_traceback(tb)
     72     else:
     73         return result[0]

~/miniconda3/envs/main/lib/python3.6/site-packages/fsspec/asyn.py in f()
     53             if callback_timeout is not None:
     54                 future = asyncio.wait_for(future, callback_timeout)
---> 55             result[0] = await future
     56         except Exception:
     57             error[0] = sys.exc_info()

~/miniconda3/envs/main/lib/python3.6/site-packages/s3fs/core.py in _mkdir(self, path, acl, create_parents, **kwargs)
    460         path = self._strip_protocol(path).rstrip('/')
    461         bucket, key, _ = self.split_path(path)
--> 462         if not key or (create_parents and not self.exists(bucket)):
    463             if acl and acl not in buck_acls:
    464                 raise ValueError('ACL not in %s', buck_acls)

~/miniconda3/envs/main/lib/python3.6/site-packages/fsspec/asyn.py in wrapper(*args, **kwargs)
    119     def wrapper(*args, **kwargs):
    120         self = obj or args[0]
--> 121         return maybe_sync(func, self, *args, **kwargs)
    122 
    123     return wrapper

~/miniconda3/envs/main/lib/python3.6/site-packages/fsspec/asyn.py in maybe_sync(func, self, *args, **kwargs)
     91         if inspect.iscoroutinefunction(func):
     92             # run coroutine while pausing this one (because we are within async)
---> 93             return _run_until_done(func(*args, **kwargs))
     94         else:
     95             # make awaitable which then calls the blocking function

~/miniconda3/envs/main/lib/python3.6/site-packages/fsspec/asyn.py in _run_until_done(coro)
     19     if sys.version_info < (3, 7):  # pragma: no cover
     20         raise RuntimeError(
---> 21             "async file systems do not work completely on py<37. "
     22             "The nested call currently underway cannot be processed. "
     23             "Please downgrade your fsspec or upgrade python."

RuntimeError: async file systems do not work completely on py<37. The nested call currently underway cannot be processed. Please downgrade your fsspec or upgrade python.
```
</details>

**Comment by v2thegreat** [comment]
Update, I tried somethings and sort of managed to get it working (reinstalled everything on a new environment and a couple of other things. This is what I'm getting as the error now. It works partially, but then gives up. It also raises a warning that my chunk sizes are too lar

<details><summary>Error Log:</summary>

```python

Exception in callback <TaskStepMethWrapper object at 0x7f9ef4076c50>()
handle: <Handle <TaskStepMethWrapper object at 0x7f9ef4076c50>()>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/latest_37/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Leaving task <Task finished coro=<sync.<locals>.f() done, defined at /home/ubuntu/miniconda3/envs/latest_37/lib/python3.7/site-packages/fsspec/asyn.py:46> result=None> does not match the current task None.

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/latest_37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/miniconda3/envs/latest_37/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/miniconda3/envs/latest_37/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/home/ubuntu/miniconda3/envs/latest_37/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
    handle = self._ready.popleft()
IndexError: pop from an empty deque

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-9-78070233c591> in <module>
     20 #     for var in merged_dataset_with_static:
     21 #         print(merged_dataset_with_static[var].encoding)
---> 22     write_zar_file(merged_dataset.chunk({'time': 30, 'latitude': 180, 'longitude': 360}), s3_path = f's3://aquantixbucket/correlations/ml_dataset/inputs_32/{year}')
     23 #     merged_dataset_with_static.to_netcdf('test_abcd.nc')
     24     break

<ipython-input-3-5c7a5767879b> in write_zar_file(dataset, s3_path, is_consolidated)
     11     s3_file_system = s3fs.S3FileSystem()
     12     store = s3fs.S3Map(root=s3_path, s3=s3_file_system, check=False)
---> 13     return dataset.to_zarr(store=store, consolidated=is_consolidated)

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/xarray/core/dataset.py in to_zarr(self, store, chunk_store, mode, synchronizer, group, encoding, compute, consolidated, append_dim)
   1660             compute=compute,
   1661             consolidated=consolidated,
-> 1662             append_dim=append_dim,
   1663         )
   1664 

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/xarray/backends/api.py in to_zarr(dataset, store, chunk_store, mode, synchronizer, group, encoding, compute, consolidated, append_dim)
   1367     # TODO: figure out how to properly handle unlimited_dims
   1368     dump_to_store(dataset, zstore, writer, encoding=encoding)
-> 1369     writes = writer.sync(compute=compute)
   1370 
   1371     if compute:

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/xarray/backends/common.py in sync(self, compute)
    159                 compute=compute,
    160                 flush=True,
--> 161                 regions=self.regions,
    162             )
    163             self.sources = []

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/dask/array/core.py in store(sources, targets, lock, regions, compute, return_stored, **kwargs)
    979 
    980         if compute:
--> 981             result.compute(**kwargs)
    982             return None
    983         else:

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    165         dask.base.compute
    166         """
--> 167         (result,) = compute(self, traverse=False, **kwargs)
    168         return result
    169 

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    450         postcomputes.append(x.__dask_postcompute__())
    451 
--> 452     results = schedule(dsk, keys, **kwargs)
    453     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    454 

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     82         get_id=_thread_get_id,
     83         pack_exception=pack_exception,
---> 84         **kwargs
     85     )
     86 

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    484                         _execute_task(task, data)  # Re-execute locally
    485                     else:
--> 486                         raise_exception(exc, tb)
    487                 res, worker_id = loads(res_info)
    488                 state["cache"][key] = res

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/dask/local.py in reraise(exc, tb)
    314     if exc.__traceback__ is not tb:
    315         raise exc.with_traceback(tb)
--> 316     raise exc
    317 
    318 

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/dask/array/core.py in store_chunk(x, out, index, lock, return_stored)
   3722 
   3723 def store_chunk(x, out, index, lock, return_stored):
-> 3724     return load_store_chunk(x, out, index, lock, return_stored, False)
   3725 
   3726 

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/dask/array/core.py in load_store_chunk(x, out, index, lock, return_stored, load_stored)
   3711     try:
   3712         if x is not None:
-> 3713             out[index] = np.asanyarray(x)
   3714         if return_stored and load_stored:
   3715             result = out[index]

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/zarr/core.py in __setitem__(self, selection, value)
   1119 
   1120         fields, selection = pop_fields(selection)
-> 1121         self.set_basic_selection(selection, value, fields=fields)
   1122 
   1123     def set_basic_selection(self, selection, value, fields=None):

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/zarr/core.py in set_basic_selection(self, selection, value, fields)
   1214             return self._set_basic_selection_zd(selection, value, fields=fields)
   1215         else:
-> 1216             return self._set_basic_selection_nd(selection, value, fields=fields)
   1217 
   1218     def set_orthogonal_selection(self, selection, value, fields=None):

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/zarr/core.py in _set_basic_selection_nd(self, selection, value, fields)
   1505         indexer = BasicIndexer(selection, self)
   1506 
-> 1507         self._set_selection(indexer, value, fields=fields)
   1508 
   1509     def _set_selection(self, indexer, value, fields=None):

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/zarr/core.py in _set_selection(self, indexer, value, fields)
   1554 
   1555             # put data
-> 1556             self._chunk_setitem(chunk_coords, chunk_selection, chunk_value, fields=fields)
   1557 
   1558     def _process_chunk(self, out, cdata, chunk_selection, drop_axes,

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/zarr/core.py in _chunk_setitem(self, chunk_coords, chunk_selection, value, fields)
   1702         with lock:
   1703             self._chunk_setitem_nosync(chunk_coords, chunk_selection, value,
-> 1704                                        fields=fields)
   1705 
   1706     def _chunk_setitem_nosync(self, chunk_coords, chunk_selection, value, fields=None):

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/zarr/core.py in _chunk_setitem_nosync(self, chunk_coords, chunk_selection, value, fields)
   1766 
   1767         # store
-> 1768         self.chunk_store[ckey] = cdata
   1769 
   1770     def _chunk_key(self, chunk_coords):

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/fsspec/mapping.py in __setitem__(self, key, value)
    151             # back compat, array.array used to work
    152             value = bytearray(value)
--> 153         self.fs.mkdirs(self.fs._parent(key), exist_ok=True)
    154         self.fs.pipe_file(key, value)
    155 

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/fsspec/spec.py in mkdirs(self, path, exist_ok)
   1075     def mkdirs(self, path, exist_ok=False):
   1076         """Alias of :ref:`FilesystemSpec.makedirs`."""
-> 1077         return self.makedirs(path, exist_ok=exist_ok)
   1078 
   1079     def listdir(self, path, detail=True, **kwargs):

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/s3fs/core.py in makedirs(self, path, exist_ok)
    486     def makedirs(self, path, exist_ok=False):
    487         try:
--> 488             self.mkdir(path, create_parents=True)
    489         except FileExistsError:
    490             if exist_ok:

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/fsspec/asyn.py in wrapper(*args, **kwargs)
    119     def wrapper(*args, **kwargs):
    120         self = obj or args[0]
--> 121         return maybe_sync(func, self, *args, **kwargs)
    122 
    123     return wrapper

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/fsspec/asyn.py in maybe_sync(func, self, *args, **kwargs)
     98         if inspect.iscoroutinefunction(func):
     99             # run the awaitable on the loop
--> 100             return sync(loop, func, *args, **kwargs)
    101         else:
    102             # just call the blocking function

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/fsspec/asyn.py in sync(loop, func, callback_timeout, *args, **kwargs)
     69     if error[0]:
     70         typ, exc, tb = error[0]
---> 71         raise exc.with_traceback(tb)
     72     else:
     73         return result[0]

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/fsspec/asyn.py in f()
     53             if callback_timeout is not None:
     54                 future = asyncio.wait_for(future, callback_timeout)
---> 55             result[0] = await future
     56         except Exception:
     57             error[0] = sys.exc_info()

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/s3fs/core.py in _mkdir(self, path, acl, create_parents, **kwargs)
    460         path = self._strip_protocol(path).rstrip('/')
    461         bucket, key, _ = self.split_path(path)
--> 462         if not key or (create_parents and not self.exists(bucket)):
    463             if acl and acl not in buck_acls:
    464                 raise ValueError('ACL not in %s', buck_acls)

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/fsspec/asyn.py in wrapper(*args, **kwargs)
    119     def wrapper(*args, **kwargs):
    120         self = obj or args[0]
--> 121         return maybe_sync(func, self, *args, **kwargs)
    122 
    123     return wrapper

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/fsspec/asyn.py in maybe_sync(func, self, *args, **kwargs)
     91         if inspect.iscoroutinefunction(func):
     92             # run coroutine while pausing this one (because we are within async)
---> 93             return _run_until_done(func(*args, **kwargs))
     94         else:
     95             # make awaitable which then calls the blocking function

~/miniconda3/envs/latest_37/lib/python3.7/site-packages/fsspec/asyn.py in _run_until_done(coro)
     29     runner = loop.create_task(coro)
     30     while not runner.done():
---> 31         loop._run_once()
     32     asyncio.tasks._current_tasks[loop] = task
     33     return runner.result()

~/miniconda3/envs/latest_37/lib/python3.7/asyncio/base_events.py in _run_once(self)
   1769         ntodo = len(self._ready)
   1770         for i in range(ntodo):
-> 1771             handle = self._ready.popleft()
   1772             if handle._cancelled:
   1773                 continue

IndexError: pop from an empty deque
```
</details>

This is the code that I'm trying to run now:

```python

def write_zar_file(dataset, s3_path, is_consolidated=True): 
    # Initilize the S3 file system
    s3_file_system = s3fs.S3FileSystem()
    store = s3fs.S3Map(root=s3_path, s3=s3_file_system, check=False)
    return dataset.to_zarr(store=store, consolidated=is_consolidated)

failed = []

for year in tqdm(range(2013, 2021)):
    input_datasets = []
    dr = pd.date_range(start=f'1/1/{year}', end=f'12/31/{year}', freq='D')
    for file in tqdm(input_dataset_files[:10]):
        try:
            dataset = read_zar_file(file)
            dataset = dataset.sel(time=dr)
            datavar = list(dataset.keys())[0]
            del dataset[datavar].encoding['chunks']
            input_datasets.append(dataset.chunk({'time': 30, 'latitude': 180, 'longitude': 360}))
        except KeyError:
            pass

    input_datasets.append(flood_dataset_2.sel(time=dr))
    merged_dataset = xr.merge(input_datasets).chunk({'time': 30, 'latitude': 180, 'longitude': 360})
    merged_dataset_with_static = xr.merge([merged_dataset, merged_static_datasets])
    write_zar_file(merged_dataset.chunk({'time': 30, 'latitude': 180, 'longitude': 360}), s3_path')
```

**Comment by amcnicho** [comment]
See https://github.com/pydata/xarray/issues/4478 for the 'pop from deque' error -- I had the same issue and reverting to an older version of fsspec solved it for me.

**Comment by max-sixty** [comment]
This can probably be closed now
